global:
  resolve_timeout: 5m
  slack_api_url: "https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK"

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "slack-notifications"
  routes:
    - match:
        severity: critical
      receiver: "slack-critical"
      continue: true
    - match:
        severity: warning
      receiver: "slack-warnings"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#monitoring"
        send_resolved: true
        title: "{{ .GroupLabels.alertname }}"
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Instance:* {{ .Labels.instance }}
          {{ end }}

  - name: "slack-critical"
    slack_configs:
      - channel: "#alerts-critical"
        send_resolved: true
        title: "[CRITICAL] {{ .GroupLabels.alertname }}"
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Instance:* {{ .Labels.instance }}
          {{ end }}

  - name: "slack-warnings"
    slack_configs:
      - channel: "#alerts-warnings"
        send_resolved: true
        title: "[WARNING] {{ .GroupLabels.alertname }}"
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Instance:* {{ .Labels.instance }}
          {{ end }}
